# Discord Stuff
enabled: true # Enable discord bot?
token: "" # Discord bot token.
server: "" # ID of discord server.
match-channel: "" # ID of channel where match embeds will be sent.

# Fallback URL for map.png images
# Example: https://raw.githubusercontent.com/TBG1000/MapImages/main/Maps/
fallback-map-images: "" # This will be used in case no map.png is found the map's directory.

# Example: https://raw.githubusercontent.com/TBG1000/MapImages/main/map_image_not_found.png
map-image-not-found: "" # Image URL to display in the embed's thumbnail if no image is found.

# Message to send  at the end of the match if an embed is created successfully.
end-match: "&6Stats: &bRevisa el canal #partidas en &1&nDiscord."
ip: "" # IP of the server to display when !ip command is used.

maps:
  allow: # List of maps for which embeds will be created. If empty, all maps will be used.
    # Example:
    # - The Towers:TE
    # - Mini Towers:TE

  blacklist: # List of map names that will be ignored when creating embeds.
    # Example:
    # - Blacklisted Map Name